# Generated by Django 4.2 on 2023-04-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationmodel',
            old_name='cv',
            new_name='CV',
        ),
        migrations.RenameField(
            model_name='informationmodel',
            old_name='fullname',
            new_name='firstName',
        ),
        migrations.RemoveField(
            model_name='informationmodel',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='informationmodel',
            name='snapchat',
        ),
        migrations.AddField(
            model_name='informationmodel',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
