# Generated by Django 4.2 on 2023-04-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_cv_informationmodel_cv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['-projectRatings']},
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='github_link',
            new_name='github_project',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project_ratings',
            new_name='projectRatings',
        ),
    ]
