# Generated by Django 4.2 on 2023-04-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_projectmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationmodel',
            name='fewWords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
