# Generated by Django 4.2 on 2023-04-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_informationmodel_fewwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'ordering': ['-projectRating']},
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='projectRatings',
            new_name='projectRating',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='skillsetmodel',
            name='skillrank',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='3', max_length=10),
        ),
    ]
